services:
    - docker
env:
    - distro: centos6
    - distro: centos7
    - distro: debian7
    - distro: debian8
    - distro: ubuntu12.04
    - distro: ubuntu14.04
    - distro: ubuntu16.04
before_install:
    - docker build -t ansible_${distro} ${distro}
    
script:
    - docker run ansible_${distro} ansible --version
    - docker run ansible_${distro} ifconfig || docker run ansible_${distro} ip addr
    - docker run ansible_${distro} ping -c 4 localhost
    
